### ISSUE TITLE
Add cool styles

### ISSUE THREAD

**Issue by pckltr** [pckltr/mental-health#1]
Check dribbble.com for an awesome design.

**Comment by Sheitak** [comment]
What exactly do you want about this project ?

**Comment by pckltr** [comment]
Hey! Thanks for asking. I want to bring awareness about mental health. Maybe have a good place to see what steps you can do make yourself feel better in the pandemic or in general.

**Comment by Sheitak** [comment]
Well, an article written on a soothing habit list maybe ? There are a few documents well provided on the internet

**Comment by RegenJacob** [comment]
I could Do that if you want

**Comment by pckltr** [comment]
@RegenJacob take it away!

**Comment by RegenJacob** [comment]
@pckltr any wishes?
